name: Trigger Cloudflare Pages Deploy
on:
  push:
    branches: [main]

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Cloudflare Pages Deployment
        run: |
          curl -X POST "${{ secrets.CF_DEPLOY_HOOK_URL }}" \
            --fail \
            --show-error \
            --silent
